const { expect } = require('chai')
const { parseAss, assTimeToSeconds } = require('../../../server/utils/assParser')

describe('assParser', () => {
  it('should parse an ASS format string with karaoke tags', () => {
    const assText = `
[Script Info]
Title: Generated by Abogen
ScriptType: v4.00+

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:00.20,0:00:01.07,Default,,,,0,karaoke,{\\kf87}Preface
Dialogue: 0,0:00:01.65,0:00:09.15,Default,,,,0,karaoke,{\\kf11}That {\\kf8}the {\\kf39}doctrine {\\kf10}of {\\kf50}original {\\kf69}sin {\\kf15}is {\\kf13}one {\\kf7}of {\\kf12}the {\\kf65}fundamental {\\kf37}truths {\\kf7}of {\\kf13}our {\\kf39}Christian {\\kf83}profession {\\kf18}has {\\kf32}always {\\kf23}been {\\kf33}owned {\\kf8}in {\\kf9}the {\\kf35}church {\\kf11}of {\\kf80}God{\\kf9}.
`

    const result = parseAss(assText)

    expect(result).to.be.an('array')
    expect(result.length).to.equal(2)

    expect(result[0].id).to.equal(1)
    expect(result[0].start).to.equal(0.2)
    expect(result[0].end).to.equal(1.07)
    expect(result[0].text).to.equal('Preface')
    expect(result[0].words.length).to.equal(1)
    expect(result[0].words[0].text).to.equal('Preface')
    expect(result[0].words[0].start).to.equal(0.2)
    expect(result[0].words[0].end).to.equal(1.07)

    expect(result[1].id).to.equal(2)
    expect(result[1].start).to.equal(1.65)
    expect(result[1].end).to.equal(9.15)
    expect(result[1].words.length).to.equal(26)
    expect(result[1].words[0].text).to.equal('That ')
    expect(result[1].words[0].start).to.equal(1.65)
    expect(result[1].words[0].end).to.be.closeTo(1.76, 0.001) // 1.65 + 0.11
    expect(result[1].words[1].text).to.equal('the ')
  })
})
